2012/03/26 14:56:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character set: 'utf8_general_ci'' in C:\xampp\yii-framework\db\CDbConnection.php:364
Stack trace:
#0 C:\xampp\yii-framework\db\CDbConnection.php(313): CDbConnection->open()
#1 C:\xampp\yii-framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 C:\xampp\yii-framework\base\CModule.php(372): CDbConnection->init()
#3 C:\xampp\yii-framework\base\CModule.php(86): CModule->getComponent('db')
#4 C:\xampp\yii-framework\gii\generators\model\ModelCode.php(54): CModule->__get('db')
#5 C:\xampp\yii-framework\web\CFormModel.php(40): ModelCode->init()
#6 C:\xampp\yii-framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 C:\xampp\yii-framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 C:\xampp\yii-framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 C:\xampp\yii-framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 C:\xampp\yii-framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 C:\xampp\yii-framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\yii-framework\web\CWebApplication.php(277): CController->run('')
#13 C:\xampp\yii-framework\web\CWebApplication.php(136): CWebApplication->runController('gii/model')
#14 C:\xampp\yii-framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\htdocs\working-sandbox\gitbox\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/working-sandbox/gitbox/index.php?r=gii/model
2012/03/26 14:57:46 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'gitbox-test.user' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `user`.
in C:\xampp\htdocs\working-sandbox\gitbox\index.php (13)
2012/03/26 15:11:51 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\yii-framework\web\CController.php:328
Stack trace:
#0 C:\xampp\yii-framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\yii-framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\yii-framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\yii-framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\yii-framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\yii-framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\yii-framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\yii-framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\yii-framework\web\CWebApplication.php(277): CController->run('view')
#9 C:\xampp\yii-framework\web\CWebApplication.php(136): CWebApplication->runController('user/view')
#10 C:\xampp\yii-framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\working-sandbox\gitbox\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/working-sandbox/gitbox/index.php?r=user/view
2012/03/27 02:02:50 [error] [exception.CException] exception 'CException' with message 'UserIdentity and its behaviors do not have a method or closure named "getTableAlias".' in C:\xampp\yii-framework\base\CComponent.php:269
Stack trace:
#0 [internal function]: CComponent->__call('getTableAlias', Array)
#1 C:\xampp\yii-framework\db\ar\CActiveRecord.php(1457): UserIdentity->getTableAlias(true)
#2 C:\xampp\htdocs\working-sandbox\gitbox\protected\components\UserIdentity.php(25): CActiveRecord->findByAttributes(Array)
#3 C:\xampp\htdocs\working-sandbox\gitbox\protected\models\LoginForm.php(53): UserIdentity->authenticate()
#4 C:\xampp\yii-framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#5 C:\xampp\yii-framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 C:\xampp\yii-framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#7 C:\xampp\htdocs\working-sandbox\gitbox\protected\controllers\SiteController.php(89): CModel->validate()
#8 C:\xampp\yii-framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#9 C:\xampp\yii-framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 C:\xampp\yii-framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 C:\xampp\yii-framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\yii-framework\web\CWebApplication.php(277): CController->run('login')
#13 C:\xampp\yii-framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#14 C:\xampp\yii-framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\htdocs\working-sandbox\gitbox\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/working-sandbox/gitbox/index.php/site/login
2012/03/27 02:05:48 [error] [exception.CDbException] exception 'CDbException' with message 'Table "user" does not have a column named "0".' in C:\xampp\yii-framework\db\schema\CDbCommandBuilder.php:568
Stack trace:
#0 C:\xampp\yii-framework\db\ar\CActiveRecord.php(1458): CDbCommandBuilder->createColumnCriteria(Object(CMysqlTableSchema), Array, '', Array, '`t`.')
#1 C:\xampp\htdocs\working-sandbox\gitbox\protected\components\UserIdentity.php(25): CActiveRecord->findByAttributes(Array)
#2 C:\xampp\htdocs\working-sandbox\gitbox\protected\models\LoginForm.php(53): UserIdentity->authenticate()
#3 C:\xampp\yii-framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#4 C:\xampp\yii-framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\yii-framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\working-sandbox\gitbox\protected\controllers\SiteController.php(89): CModel->validate()
#7 C:\xampp\yii-framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#8 C:\xampp\yii-framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#9 C:\xampp\yii-framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#10 C:\xampp\yii-framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\yii-framework\web\CWebApplication.php(277): CController->run('login')
#12 C:\xampp\yii-framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#13 C:\xampp\yii-framework\base\CApplication.php(158): CWebApplication->processRequest()
#14 C:\xampp\htdocs\working-sandbox\gitbox\index.php(13): CApplication->run()
#15 {main} REQUEST_URI=/working-sandbox/gitbox/index.php/site/login
2012/03/27 02:29:38 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\yii-framework\web\CController.php:328
Stack trace:
#0 C:\xampp\yii-framework\web\CController.php(301): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\yii-framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 C:\xampp\yii-framework\web\filters\CFilter.php(41): CFilterChain->run()
#3 C:\xampp\yii-framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\yii-framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\yii-framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\yii-framework\web\CController.php(283): CFilterChain->run()
#7 C:\xampp\yii-framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\yii-framework\web\CWebApplication.php(277): CController->run('view')
#9 C:\xampp\yii-framework\web\CWebApplication.php(136): CWebApplication->runController('user/view')
#10 C:\xampp\yii-framework\base\CApplication.php(158): CWebApplication->processRequest()
#11 C:\xampp\htdocs\working-sandbox\gitbox\index.php(13): CApplication->run()
#12 {main} REQUEST_URI=/working-sandbox/gitbox/index.php/user/view
2012/03/27 02:29:50 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii-framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\yii-framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii-framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii-framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii-framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii-framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii-framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\yii-framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\yii-framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\yii-framework\web\CWebApplication.php(136): CWebApplication->runController('user/admin')
#9 C:\xampp\yii-framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\working-sandbox\gitbox\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/working-sandbox/gitbox/index.php/user/admin
